#!/usr/bin/env python3
"""
Analyze Telegram forum topics from collected data.
Uses ~/all_topics_masass18.json generated by collect_topics.py
"""

import argparse
import csv
import json
from pathlib import Path


def load_topics():
    """Load topics from JSON file."""
    data_path = Path.home() / "all_topics_masass18.json"
    if not data_path.exists():
        print(f"❌ Data file not found: {data_path}")
        print("   Run collect_topics.py first!")
        return {}, ""

    with open(data_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    return data.get('topics', {}), data.get('group_title', 'masass18')


def format_topic(tid, t, show_all=False):
    """Format topic for display."""
    lines = [
        f"  📋 Topic #{tid}: {t['title']}",
        f"     unread: {t['unread_count']:,} | total_msgs: {t['total_messages']:,} | top_msg: {t.get('top_message_id', t.get('top_message', 0)):,}",
        f"     closed: {t['closed']} | hidden: {t['hidden']}",
    ]
    if show_all:
        lines.append(f"     raw: {json.dumps(t, ensure_ascii=False)}")
    return "\n".join(lines)


def search_topics(topics, query):
    """Search topics by title (case-insensitive)."""
    query_lower = query.lower()
    results = []
    for tid, t in topics.items():
        if query_lower in t['title'].lower():
            results.append((tid, t))
    results.sort(key=lambda x: x[1]['unread_count'], reverse=True)
    return results


def get_stats(topics):
    """Calculate statistics."""
    total = len(topics)
    arabic = sum(1 for t in topics.values() if any('\u0600' <= c <= '\u06FF' for c in t['title']))
    english = sum(1 for t in topics.values() if any('a' <= c.lower() <= 'z' for c in t['title']) and not any('\u0600' <= c <= '\u06FF' for c in t['title']))
    mixed = total - arabic - english
    unread_topics = sum(1 for t in topics.values() if t['unread_count'] > 0)
    total_unread = sum(t['unread_count'] for t in topics.values())
    closed = sum(1 for t in topics.values() if t['closed'])
    hidden = sum(1 for t in topics.values() if t['hidden'])
    total_msgs = sum(t['total_messages'] for t in topics.values())

    return {
        'total': total, 'arabic': arabic, 'english': english, 'mixed': mixed,
        'unread_topics': unread_topics, 'total_unread': total_unread,
        'closed': closed, 'hidden': hidden, 'total_messages': total_msgs
    }


def main():
    parser = argparse.ArgumentParser(description="Analyze Telegram forum topics from masass18")
    sub = parser.add_subparsers(dest='cmd', required=True, help='Commands')

    # stats
    sub.add_parser('stats', help='Show overall statistics')

    # search
    p = sub.add_parser('search', help='Search topics by title')
    p.add_argument('query', help='Search query')

    # unread
    p = sub.add_parser('unread', help='List topics with unread messages')
    p.add_argument('--min', type=int, default=1, dest='min_unread', help='Minimum unread count')

    # oldest
    p = sub.add_parser('oldest', help='Show oldest N topics (by top_message_id)')
    p.add_argument('n', type=int, default=10, nargs='?')

    # newest
    p = sub.add_parser('newest', help='Show newest N topics (by top_message_id)')
    p.add_argument('n', type=int, default=10, nargs='?')

    # export
    p = sub.add_parser('export', help='Export topics to CSV or JSON')
    p.add_argument('--format', choices=['csv', 'json'], default='csv')
    p.add_argument('--output', help='Output file path')

    # topic detail
    p = sub.add_parser('topic', help='Show details for one topic')
    p.add_argument('id', type=int, help='Topic ID')

    # by-language
    p = sub.add_parser('by-language', help='Filter by title language')
    p.add_argument('lang', choices=['ar', 'en', 'mixed'])

    args = parser.parse_args()

    topics, group_title = load_topics()
    if not topics:
        return

    print(f"📂 Loaded {len(topics)} topics from {group_title}\n")

    if args.cmd == 'stats':
        s = get_stats(topics)
        print("📊 Statistics:")
        print(f"  Total topics:        {s['total']:,}")
        print(f"  Arabic titles:       {s['arabic']:,}")
        print(f"  English titles:      {s['english']:,}")
        print(f"  Mixed/Other:         {s['mixed']:,}")
        print(f"  Topics with unread:  {s['unread_topics']:,} (total unread: {s['total_unread']:,})")
        print(f"  Closed topics:       {s['closed']:,}")
        print(f"  Hidden topics:       {s['hidden']:,}")
        print(f"  Total messages:      {s['total_messages']:,}")

    elif args.cmd == 'search':
        results = search_topics(topics, args.query)
        print(f"🔍 Found {len(results)} matching '{args.query}':\n")
        for tid, t in results[:50]:
            print(format_topic(tid, t))
            print()
        if len(results) > 50:
            print(f"... and {len(results) - 50} more")

    elif args.cmd == 'unread':
        filtered = [(tid, t) for tid, t in topics.items() if t['unread_count'] >= args.min_unread]
        filtered.sort(key=lambda x: x[1]['unread_count'], reverse=True)
        print(f"📬 Topics with unread ≥ {args.min_unread}: {len(filtered)}\n")
        for tid, t in filtered:
            print(f"  #{tid}: {t['title']} — unread: {t['unread_count']:,}, total: {t['total_messages']:,}")

    elif args.cmd == 'oldest':
        sorted_topics = sorted(topics.items(), key=lambda x: x[1].get('top_message_id', x[1].get('top_message', 0)))
        print(f"📜 Oldest {args.n} topics:\n")
        for tid, t in sorted_topics[:args.n]:
            top_msg = t.get('top_message_id', t.get('top_message', 0))
            print(f"  #{tid}: {t['title']} (top_msg: {top_msg:,})")

    elif args.cmd == 'newest':
        sorted_topics = sorted(topics.items(), key=lambda x: x[1].get('top_message_id', x[1].get('top_message', 0)), reverse=True)
        print(f"✨ Newest {args.n} topics:\n")
        for tid, t in sorted_topics[:args.n]:
            top_msg = t.get('top_message_id', t.get('top_message', 0))
            print(f"  #{tid}: {t['title']} (top_msg: {top_msg:,})")

    elif args.cmd == 'export':
        output = Path(args.output) if args.output else Path.home() / f"masass18_topics.{args.format}"
        if args.format == 'csv':
            with open(output, 'w', encoding='utf-8', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['ID', 'Title', 'Unread', 'Total_Messages', 'Closed', 'Hidden', 'Top_Message_ID'])
                for tid, t in sorted(topics.items(), key=lambda x: int(x[0])):
                    writer.writerow([tid, t['title'], t['unread_count'], t['total_messages'],
                                                    'Yes' if t['closed'] else 'No', 'Yes' if t['hidden'] else 'No',
                                                    t.get('top_message_id', t.get('top_message', 0))])
        else:
            with open(output, 'w', encoding='utf-8') as f:
                json.dump(topics, f, ensure_ascii=False, indent=2)
        print(f"💾 Exported {len(topics)} topics to {output}")

    elif args.cmd == 'topic':
        tid = str(args.id)
        if tid in topics:
            print(f"📋 Topic #{tid} details:\n")
            print(format_topic(tid, topics[tid], show_all=True))
        else:
            print(f"❌ Topic {tid} not found")

    elif args.cmd == 'by-language':
        filtered = []
        for tid, t in topics.items():
            has_ar = any('\u0600' <= c <= '\u06FF' for c in t['title'])
            has_en = any('a' <= c.lower() <= 'z' for c in t['title'])
            if args.lang == 'ar' and has_ar and not has_en:
                filtered.append((tid, t))
            elif args.lang == 'en' and has_en and not has_ar:
                filtered.append((tid, t))
            elif args.lang == 'mixed' and has_ar and has_en:
                filtered.append((tid, t))
        print(f"🌐 Topics with {args.lang} titles: {len(filtered)}\n")
        for tid, t in filtered:
            print(f"  #{tid}: {t['title']}")


if __name__ == '__main__':
    main()